import 'server-only'
import { createServiceClient } from '@/lib/supabase/service'
import { DrillDocSchema } from './object-schema'
import { renderThumbnailPng } from './thumbnail'

/**
 * Renders a board and stores it as the drill's library thumbnail.
 *
 * Thumbnails used to be produced only by the editor's debounced regeneration,
 * so a drill that was generated by Pep and never opened had no preview at all —
 * which was every drill in the library bar the ones that happened to be edited.
 * Creation paths call this directly instead.
 *
 * `field` and `objects` are taken raw and validated here, so callers can hand
 * over whatever the database returned without parsing it themselves.
 *
 * Never throws: a missing preview is not worth failing a drill creation over.
 * Returns the stored path, or null if the thumbnail could not be produced.
 */
export async function writeDrillThumbnail(
  drillId: string,
  clubId: string,
  field: unknown,
  objects: unknown,
): Promise<string | null> {
  try {
    const parsed = DrillDocSchema.safeParse({ field, objects })
    if (!parsed.success) {
      console.error('[thumbnail] drill doc failed validation', drillId, parsed.error.message)
      return null
    }

    const png = await renderThumbnailPng(parsed.data.field, parsed.data.objects)
    const path = `${clubId}/${drillId}.png`
    const svc = createServiceClient()

    const { error: uploadError } = await svc.storage
      .from('drill-thumbnails')
      .upload(path, png, { contentType: 'image/png', upsert: true })
    if (uploadError) throw uploadError

    const { error: updateError } = await svc
      .from('drills').update({ thumbnail_path: path }).eq('id', drillId)
    if (updateError) throw updateError

    return path
  } catch (e) {
    // Logged rather than swallowed. The previous code ignored the upload result
    // entirely, so a broken bucket looked identical to a drill that simply had
    // no preview yet.
    console.error('[thumbnail] failed for drill', drillId, e)
    return null
  }
}
